# Generated by Django 4.2.13 on 2024-05-11 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('comment', 'user')},
        ),
    ]
