# Generated by Django 4.2.13 on 2024-05-12 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_alter_rate_rating_alter_rate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('comment', 'user', 'rating')},
        ),
    ]
