# Generated by Django 4.2.13 on 2024-05-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_created',), 'verbose_name_plural': 'Comments'},
        ),
    ]
