# Generated by Django 4.2.13 on 2024-05-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'ordering': ('-date_created',),
                'verbose_name_plural': 'Comments'
            },
        ),
    ]
