# Generated by Django 4.2.13 on 2024-05-09 11:21

import accounts.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, max_length=500, null=True, quality=95, scale=0.5, size=[320, 240], storage=accounts.models.OverwriteStorage(), upload_to=accounts.models.profile_avatar_path),
        ),
    ]
